config/routes.rb
Highrise::Application.routes.draw do
  devise_for :admins
  namespace :highrise do
   match "tasks" => "highrise#tasks"
   match "users" => "highrise#users"
  end

  root :to => "highrise#tasks"

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/highrise_controller.rb
class HighriseController < ApplicationController

 before_filter :authenticate_admin!
 layout 'default'

 def tasks
   @tasks = Highrise::Task.all
 end

 def users
   @users = Highrise::User.all
 end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/highrise_helper.rb
module HighriseHelper
end

app/views/highrise/tasks.html.erb
<div><h1>All Task's List</h1></div>
<table>
 <thead><tr>
  <td><b>Task Description</b></td>
  <td><b>Due Date</b></td>
</tr></thead>
<%@tasks.each do |task|%>
 <tr><td> <%= task.body%></td><td> <%= task.due_at%></td></tr> 
<%end%>
</table>

app/views/highrise/users.html.erb
<div><h1>User's List</h1></div>
<table>
 <thead><tr><td><b>User Name</b></td></tr></thead>
<%@users.each do |user|%>
 <tr><td> <%= user.name%></td></tr> 
<%end%>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Highrise</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/default.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Highrise</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>	
<div align='right'><%= link_to 'logout' , destroy_admin_session_path,:method=>:delete %></div>
<%= yield %>

</body>
</html>